
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasan Mangrove
 */
public class RotateDemo extends javax.swing.JFrame {

    /**
     * Creates new form RotateDemo
     */
    public RotateDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        imageLoader1 = new ImageLoader();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout imageLoader1Layout = new javax.swing.GroupLayout(imageLoader1);
        imageLoader1.setLayout(imageLoader1Layout);
        imageLoader1Layout.setHorizontalGroup(
            imageLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        imageLoader1Layout.setVerticalGroup(
            imageLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(imageLoader1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            imageLoader1.loadImage("C:\\Users\\Hasan Mangrove\\Desktop\\movie.jpg");
        } catch (IOException ex) {
            Logger.getLogger(RotateDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        imageLoader1.invalidate();
    }//GEN-LAST:event_formWindowOpened

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        imageLoader1.rotateImage(jSlider1.getValue());
    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImageLoader imageLoader1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
